version: "3"
services:
  adn3:
    container_name: hyperlinks
    image: mijara/hyperlinks
    restart: on-failure
    command: bash -c "python manage.py migrate && gunicorn hyperlinks.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"

