# Generated by Django 2.1 on 2018-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField(unique=True)),
                ('keywords', models.CharField(max_length=2048, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
